//Constants for the reducers and actions

export const START_REQUEST = "START_REQUEST";
export const END_REQUEST = "END_REQUEST";
export const RESP_ERROR = "RESP_ERROR";
export const MSG_ERROR = "MSG_ERROR";

//customerList
export const GET_CUSTOMER_LIST = "GET_CUSTOMER_LIST";
export const GET_COUNTRY_LIST = "GET_COUNTRY_LIST";
export const GET_STATE_LIST = "GET_STATE_LIST";
export const GET_ATECO_CODE_LIST = "GET_ATECO_CODE_LIST";
export const GET_CUSTOMER_DETAILS = "GET_CUSTOMER_DETAILS";
export const UPDATE_CUSTOMER_DATA = "UPDATE_CUSTOMER_DATA";
export const MANUALLY_ADD_CUSTOMER = "MANUALLY_ADD_CUSTOMER";
export const ADD_NEW_CUSTOMER = "ADD_NEW_CUSTOMER";
export const CUSTOMER_FOLDER_LIST = "CUSTOMER_FOLDER_LIST";
export const CUSTOMER_FOLDER_EXPAND = "CUSTOMER_FOLDER_EXPAND";
export const GET_LEGAL_NATURE = "GET_LEGAL_NATURE";
export const CUSTOMER_FOLDER_DETAILS = "CUSTOMER_FOLDER_DETAILS";
export const MANDATORY_DOC_UPLOAD = "MANDATORY_DOC_UPLOAD";
export const OTHER_DOC_UPLOAD = "OTHER_DOC_UPLOAD";
export const CUSTOMER_QUESTION_LIST = "CUSTOMER_QUESTION_LIST";
