/* eslint-disable prettier/prettier */
import LocalizedStrings from 'react-native-localization';

let strings = new LocalizedStrings({
  'en-US': {
    AppName: 'Alavie',
    logoutConfirmMsg: 'Are you sure you want to logout?',
    appExitMsg: 'Are you sure you want to exit from app?',
    login: 'Login',
    userEmail: 'User Email',
    password: 'Password',
    userFName: 'First Name',
    userLName: 'Last Name',
    userPhn: 'Contact Number',
    reopenTicket: 'Reopen Ticket',
    forgotPassword: 'Forgot Password?',
    forgotPass: 'Forgot Password',
    search: 'Search',
    NA: 'N/A',
    forgotPassText:
      'Please, enter your email address. You will receive a link to create a new password via email.',
    send: 'SEND',
    backToLogin: 'Back to Login',
    uniqueId: "Client's Unique ID",
    changeUniqueId: 'Change Client Unique ID',
    placeholderUniqueId: "Enter Client's Unique ID",
    uniquePortalId: 'Client Portal URL',
    placeHolderPortalId: 'Enter Client Portal URL',
    changePortalURL: 'Change Client Portal URL',
    uploadedBy: 'Uploaded By',
    uploadedOn: 'Upload On',
    signatureType: 'Customer Signature',
    docType: 'Document Type',
    uniqueIdStatic:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    next: 'NEXT',
    cancel: 'CANCEL',
    change: 'CHANGE',
    dashboard: 'Dashboard',
    identification: 'Identification',
    operations: 'Operations',
    aml: 'AML',
    support: 'Support',
    risk: 'Risk',
    notifications: 'Notifications',
    logout: 'Logout',
    customers: 'Customers',
    customersFolder: 'Customers Folder',
    ticketsReq: 'Tickets Requested',
    chatBot: 'Chatbot',
    english: 'ENGLISH',
    privacyPolicy: 'Privacy Policy',
    termsConditions: 'Terms & Conditions',
    myProfile: 'My Profile',
    editProfile: 'Edit Profile',
    updateProfile: 'UPDATE PROFILE',
    changePass: 'Change Password',
    oldPass: 'Old Password',
    newPass: 'New Password',
    confirmnewPass: 'Confirm New Password',
    show: 'Show',
    definitive: 'Definitive',
    temporary: 'Temporary',
    canceled: 'Cancelled',
    addcustomer: 'Add Customer',
    share: 'Share',
    businessName: 'Business Name',
    subsituteType: 'Substitute Type',
    filterBySpecificReasons: 'Filter by specific reasons',
    allReasons: 'All Reasons',
    notverySignificant: 'Not very significant',
    aenanOption: 'Aenean sed erat nec odio',
    loremisum: 'Lorem ipsum dolor sit amet',
    inMAxNisi: 'in maximum nisi',
    viewCustomer: 'View Customer',
    addCustomer: 'New Customer',
    newTran: 'New Transaction',
    modifyCust: 'Modify Customer',
    manuallAddCust: 'Manually add Customer',
    selectCust: 'Select Customer',
    nonComplienceToolTipData:
      'Identity Document or Risk Assesment is missing or AML declaration has no signature.',
    partialComplienceToolTipData:
      'Identification document exists but it is expired, or risk assessment exists but not updated',
    profPerf: 'Professional Performance',
    profperfTitle1: 'Accounting Consultancy',
    profperfTitle2: 'Drafting Budget Assistants',
    profperfTitle3: 'Tax Consultancy',
    profperfTitle4: 'Company Consultancy for Mergers',
    profperfTitle5: 'Contractual Consultancy for mergers',
    value: 'Value',
    valueData1: 'Indeterminate',
    valueData2: 'Determinate',
    riskAsst: 'Risk Assessment',
    riskAsst1: 'Low',
    riskAsst2: 'Medium',
    riskAsst3: 'High',
    listedUserList: 'All Users List',
    nonCompl: 'Non Compliance',
    partialComp: 'Partially Compliance',
    ResiAdd: 'Residence Address',
    HeadQAdd: 'Headquarters Address',

    mainData: 'Main Data',
    fiscal: 'Fiscal code',
    vatNo: 'VAT Number',
    firstN: 'First Name',
    lastN: 'Last Name',
    commonFB: 'Common Foreign Birth',
    performAct: 'Performed Activity',
    businesN: 'Business Name',
    legalN: 'Legal Nature',
    businesS: 'Business Sector',
    muniFH: 'Municipality of foreign headquarters',
    DOB: 'Date of Birth',
    BS: 'Birth State',
    BP: 'Birth Province',
    AC: 'Ateco Code',
    ERD: 'End of Relationship Date',
    HS: 'Home state',
    Residncy: 'Residence',
    ReState: 'Residence State',
    CFR: 'Common Foreign Residence',
    Star: '*',
    PR: 'Postcode Residence',
    DER: 'Domicile equal to residence',
    previous: 'PREVIOUS',
    update: 'UPDATE',
    customerFolderDetails: 'Customer Folder',

    invoice: 'Invoice',
    invoiceUpload: 'Upload CSV',
    profType: 'Type',
    invoiceCurrency: 'Currency',
    regiDate: 'Registration Date',
    invoiceRegiDate: 'Registration Date',
    invoiceDesc: 'Description',
    invoiceDesCountry: 'Destination Country',
    invoiceFractional: 'Fractional',
    invoiceSelectFractional: 'Select Fractional',
    invoiceDesProvince: 'Destination Province',
    invoiceSelectType: 'Select Type',

    addCustomerFirstPolicy:
      'The customer is reluctant to provide or refuses to provide information, data and documents commonly acquired for the execution of the operation or for the performance regulations?',
    addCustomerSecondPolicy:
      'The customer shows an unusual familiarity with the safeguards provided for by the legislation on customer due diligence, data recording and reporting of suspicious transactions, or does it ask repeated questions regarding the methods of application of these safeguards?',
    addCustomerThirdPolicy:
      'The customer demonstrates that he does not have adequate knowledge of the nature, object or purpose of the professional service requested, raising the doubt that can he conceal that he is acting with illicit purposes on behalf of a third party?',
    yes: 'Yes',
    no: 'No',
    dateIdent: 'Date of Identification',
    docUpload: 'Upload Documents',
    sociaty: 'Society',
    sendCustomerDetail: 'Send',
    naturalPerson: 'Natural Person / Sole Proprietorship',
    folderDetails: 'Folder Details',
    businesSector: 'Business Sector',
    beneficialOWner: 'Beneficial Owner',
    legalRepresentative: 'Legal Representative',
    specificRisk: 'Specific Risk',
    typeVerification: 'Type of Verification',
    customerFolder: 'Folder Listing',
    customerName: 'Customer Name',
    documentStatus: 'Document Status',
    yearWise0: '2022',
    yearWise1: '2021',
    yearWise2: '2020',
    yearWise3: '2019',
    yearWise4: '2018',
    yearWise5: '2017',
    yearWise6: '2016',
    yearWise7: '2015',
    documentStatusValCompliance: 'Compliance',
    documentStatusValNonCompliance: 'Non Compliance',
    infoNonComplDetail:
      'Identity Document or Risk Assesment is missing or AML declaration has no signature.',
    mandatoryDocuments: 'Mandatory Documents',
    otherDocuments: 'Other Documents',
    upload: 'Upload',
    shareall: 'Share All',
    tickets: 'Tickets',
    createTicket: 'CREATE NEW TICKET',
    subjectType: 'Subject Type',
    createTickets: 'Create New Ticket',
    createUserTickets: 'Create Ticket',
    ticketsConversations: 'Ticket Conversation',
    selectSupportType: 'Select Support Type',
    chatbot: 'Chatbot',
    myRisk: 'My Risk',
    customerRisk: 'Customer Risk',
    transactionRisk: 'Customer Transaction Risk',
    reports: 'Reports',
    verificationCode: 'Verification',
    placeHolderOtp: 'Enter OTP',
    verifyOtp: 'VERIFY OTP',
    verificationCodeDetails:
      'Please type verification code sent to your registered email address',
    resendOtp: 'Resend OTP',

    //Validation messages:
    selectTheInvoiceDocBlankError: 'Please choose the invoice document',
    selectTheInvoiceTypeBlankError: 'Please select the invoice type',
    selectTheInvoiceRegBlankError: 'Please select the registration date',
    invoiceCurrencyTypeBlankError: 'Please select the invoice currency type',
    invoiceCountryTypeBlankError: 'Please select the country',
    invoiceDescTypeBlankError: 'Please enter the description',

    uniqueBlankError: 'Please enter unique id',
    HeadQAddBlankValidation: 'Please enter headquarters Address',
    portalurlBlankErr: 'Please enter client portal url',
    portalurlValidErr: 'Please enter valid client portal url',
    emailBlankError: 'Please enter email',
    emailValidError: 'Please enter valid email',
    contactNumLengthError: 'Contact number must be 10 digit long',
    passwordBlankError: 'Please enter password',
    oldPassBlankError: 'Please enter old password',
    newPassBlankError: 'Please enter new password',
    selectTheCustomerBlankError: 'Please select the customer first',
    selectTheNoteBlankError: 'Please enter the notes detail',
    newPassLengthError: 'The new password must be at least 8 characters',
    newStrongPassError:
      'Please add atleast one uppercase, one special character, one number in new password',
    confirmBlankError: 'Please enter confirm password',
    passwordNotSameErr: 'New password and confirm password should be same',
    firstNameBlankError: 'Please enter first name',
    lastNameBlankError: 'Please enter last name',
    contactNumBlankError: 'Please enter contact number',
    fnameValidError: 'Please enter valid first name',
    lNameValidError: 'Please enter valid last name',
    selectMediaType: 'Please select media type.',
    otpBlankError: 'Please enter OTP',
    otpLengthError:
      'The selected OTP is invalid because it must be 5 digit long',
    ageValidError: 'User must be 18 years old',
    //customer validation msg
    fiscalCodeBlankError: 'Please enter fiscal code',
    vatCodeBlankError: 'Please enter vat code',
    userDOBBlankError: 'Please enter the user date of birth',
    userERDBlankError: 'Please enter the relation end date',
    commonForeignBlankError: 'Please enter common foreign birth',
    birthCounteryBlankError: 'Please enter the user birth country',
    birthStateBlankError: 'Please enter the user state code',
    performedActivityBlankError: 'Please enter the performed activity',
    businessNameBlankError: 'Please enter business name',
    legalNatureBlankError: 'Please enter the legal nature',
    businessSectorBlankError: 'Please enter the business sector',
    atecoCodeBlankError: 'Please select the ateco code',
    MFHBlankError: 'Please enter the municipality of foreign headquarters',
    CFRBlankError: 'Please enter common foreign regidency',
    postCodeBlankError: 'Please enter user post code',
    numberOnlyError: 'Legal code accept only the number',

    //Dashboard Titles
    monthwiseTitle: 'Month wise',
    customerStatics: 'Customers Statistics',
    myRiskTitle: 'My Risk Graph',
    recentTransation: 'Recent Transactions',
    recentNews: 'Recent News',
    viewAll: 'View All',

    //API messages:
    somethingWentWrong: 'Something went wrong, Please try again later',
    internetNotAvail: 'Please Check Your Internet Connection.',
    ticketSubject: 'Ticket Subject',
    ticketDetail: 'Ticket Details...',
    closeTicket: 'Close Ticket',
    news: 'News',
    verificationTypeFirst: 'Ordinary',
    verificationTypeSecond: 'Simplified',
    verificationTypeThird: 'Strengthened',

    //filter options
    all: 'All',
    compliance: 'Compliance',
    nonCompliance: 'Non Compliance',
    partialCompliance: 'Partially Compliance',
    open: 'Open',
    close: 'Closed',
    add: 'Add',

    domData: 'Domicile',
    domCountry: 'Country of Domicile',
    domProvince: 'Province of Domicile',
    domMFD: 'Municipality of Foreign Domicile',
    domZipCode: 'Domicile Zipcode',
    domHomeAdd: 'Home address',

    //support type
    operationalQuery: ' Operational Related Query',
    contractQuery: ' Contract Related Query',
    transactionQuery: ' Transactional Related Query',
    notAble: 'Not available',

    //ticket validation
    ticketSubjectBlankError: 'Please enter ticket subject',
    ticketTypeBlankError: 'Please enter ticket type',
    ticketDetailsBlankError: 'Please enter ticket details',
    supportTypeSelection: 'Choose the support type',
    dateIdentity: 'Please select the date identity',
    ticketDetailsError: 'Ticket details must be combination of characters',
    ticketSubjectError: 'Ticket subject must be combination of characters',
    excelUpload: 'Upload Excel',
    imageUpload: 'Take Picture',
    noData: 'No Data Available',
    noCust: 'No Customer Available',

    //headingText
    typeofsubject: 'Type of subject',
    seriesofQuestion: 'Series Of Questions',
    madeBy: 'Made By',
    notes: 'Notes',
    reason: 'Reason',
    invoiceSelectReason: 'Selected Reason',
    prof: 'Professional',
    selectedProf: 'Selected Professional',
    uploadDoc: 'Upload document',
    custCounty: 'Customer country',
    custProvinces: 'customer Provinces',
    amountType: 'Amount type',
    amount: 'Amount',
    coin: 'Coin',
    paymentMethod: 'Payment Method',
    newPerfo: 'New Performance',
    tradeName: 'Trade name',
    attorney: 'Attorney',
    selectType: 'Select Type',
    uploadAnotherDoc: 'Upload another document',
    uploadChamberDoc: 'Upload Chamber of commerce document',
    selectFromExis: 'Select from existing',
    addNew: 'Add New',
    stateBirth: 'State of birth',
    mBirthabroad: 'Municipality of birth abroad',
    updateType: 'Update type',
    updateMan: 'Upload manually',
    resState: 'State of Residence',
    resCity: 'City of residence',
    pCodeRes: 'Postal code of residence',
    domResi: 'Domicile equal to residence',
    typeDoc: 'Type of document',
    headquarter: 'Headquarters',
    munHead: 'Municipality of Headquarter',
    address: 'Address',
    state: 'State',
    city: 'City',
    identityDoc: 'Identity Document',
    nominyData: 'Date of Nomination',
    identiData: 'Identification date',
    uploadChamberDoc: 'Upload Chamber of Commerce Document',
    provResi: 'Province of residence',
    selectPro: 'Select Province',
    effOwner: 'Effective owner',
    addSub: 'ADD SUBJECT',
    dataAcqu: 'Data acquired through',
    engageStartData: 'Engagement start date',
    endDateassign: 'End date of assignment',
  },
  fr: {
    AppName: 'Alavie',
    logoutConfirmMsg: 'Are you sure you want to logout?',
    appExitMsg: 'Are you sure you want to exit from app?',
    login: 'Login',
    userEmail: 'User Email',
    password: 'Password',
    userFName: 'First Name',
    userLName: 'Last Name',
    userPhn: 'Contact Number',
    forgotPassword: 'Forgot Password?',
    forgotPass: 'Forgot Password',
    forgotPassText:
      'Please, enter your email address. You will receive a link to create a new password via email.',
    send: 'SEND',
    backToLogin: 'Back to Login',
    uniqueId: "Client's Unique ID",
    changeUniqueId: 'Change Client Unique ID',
    placeholderUniqueId: "Enter Client's Unique ID",
    uniquePortalId: 'Client Portal URL',
    placeHolderPortalId: 'Enter Client Portal URL',
    changePortalURL: 'Change Client Portal URL',
    uniqueIdStatic:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    next: 'NEXT',
    previous: 'PREVIOUS',
    update: 'UPDATE',
    cancel: 'CANCEL',
    change: 'CHANGE',
    dashboard: 'Dashboard',
    identification: 'Identification',
    operations: 'Operations',
    aml: 'AML',
    support: 'Support',
    risk: 'Risk',
    notifications: 'Notifications',
    logout: 'Logout',
    customers: 'Customers',
    customersFolder: 'Customers Folder',
    ticketsReq: 'Tickets Requested',
    chatBot: 'Chatbot',
    english: 'ENGLISH',
    privacyPolicy: 'Privacy Policy',
    termsConditions: 'Terms & Conditions',
    myProfile: 'My Profile',
    editProfile: 'Edit Profile',
    updateProfile: 'UPDATE PROFILE',
    changePass: 'Change Password',
    oldPass: 'Old Password',
    newPass: 'New Password',
    confirmnewPass: 'Confirm New Password',
    show: 'Show',
    definitive: 'Definitive',
    temporary: 'Temporary',
    canceled: 'Cancelled',
    addcustomer: 'Add Customer',
    share: 'Share',
    businessName: 'Business Name',
    subsituteType: 'Substitute Type',
    filterBySpecificReasons: 'Filter by specific reasons',
    allReasons: 'All Reasons',
    notverySignificant: 'Not very significant',
    aenanOption: 'Aenean sed erat nec odio',
    loremisum: 'Lorem ipsum dolor sit amet',
    inMAxNisi: 'in maximum nisi',
    viewCustomer: 'View Customer',
    folderDetails: 'Folder Details',
    businesSector: 'Business Sector',
    beneficialOWner: 'Beneficial Owner',
    legalRepresentative: 'Legal Representative',
    specificRisk: 'Specific Risk',
    typeVerification: 'Type of Verification',
    customerFolder: 'Folder Listing',
    customerName: 'Customer Name',
    documentStatus: 'Document Status',
    documentStatusValCompliance: 'Compliance',
    documentStatusValNonCompliance: 'Non Compliance',
    infoNonComplDetail:
      'Identity Document or Risk Assesment is missing or AML declaration has no signature.',
    mandatoryDocuments: 'Mandatory Documents',
    otherDocuments: 'Other Documents',
    upload: 'Upload',
    shareall: 'Share All',
    tickets: 'Tickets',
    createTicket: 'CREATE NEW TICKET',
    subjectType: 'Subject Type',
    createTickets: 'Create New Ticket',
    ticketsConversations: 'Ticket Conversation',
    selectSupportType: 'Select Support Type',
    chatbot: 'Chatbot',
    verificationCode: 'Verification',
    placeHolderOtp: 'Enter OTP',
    verifyOtp: 'VERIFY OTP',
    verificationCodeDetails:
      'Please type verification code sent to your registered email address',
    resendOtp: 'Resend OTP',
    //Validation messages:
    uniqueBlankError: 'Please enter unique id',
    portalurlBlankErr: 'Please enter client portal url',
    HeadQAddBlankValidation: 'Please enter headquarters Address',
    portalurlValidErr: 'Please enter valid client portal url',
    emailBlankError: 'Please enter email',
    emailValidError: 'Please enter valid email',
    passwordBlankError: 'Please enter password',
    oldPassBlankError: 'Please enter old password',
    selectTheNoteBlankError: 'Please enter the notes detail',
    selectTheCustomerBlankError: 'Please select the customer first',
    newPassBlankError: 'Please enter new password',
    newPassLengthError: 'The new password must be at least 8 characters',
    newStrongPassError:
      'Please add atleast one uppercase, one special character, one number in new password',
    confirmBlankError: 'Please enter confirm password',
    passwordNotSameErr: 'New password and confirm password should be same',
    firstNameBlankError: 'Please enter first name',
    lastNameBlankError: 'Please enter last name',
    contactNumBlankError: 'Please enter contact number',
    contactNumLengthError: 'Contact number must be 10 digit long',
    fnameValidError: 'Please enter valid first name',
    lNameValidError: 'Please enter valid last name',
    selectMediaType: 'Please select media type.',
    otpBlankError: 'Please enter OTP',
    otpLengthError:
      'The selected OTP is invalid because it must be 5 digit long',
    ageValidError: 'User must be 18 years old',
    nonComplienceToolTipData:
      'Identity Document or Risk Assesment is missing or AML declaration has no signature.',
    partialComplienceToolTipData:
      'Identification document exists but it is expired, or risk assessment exists but not updated',
    //Dashboard Titles
    monthwiseTitle: 'Month wise',
    customerStatics: 'Customers Statistics',
    myRiskTitle: 'My Risk Graph',
    recentTransation: 'Recent Transactions',
    recentNews: 'Recent News',
    viewAll: 'View All',
    ticketSubject: 'Ticket Subject',
    ticketDetail: 'Ticket Details...',
    myRisk: 'My Risk',
    customerRisk: 'Customer Risk',
    transactionRisk: 'Customer Transaction Risk',
    reports: 'Reports',
    news: 'News',

    selectTheInvoiceDocBlankError: 'Please choose the invoice document',
    selectTheInvoiceTypeBlankError: 'Please select the invoice type',
    selectTheInvoiceRegBlankError: 'Please select the registration date',
    invoiceCurrencyTypeBlankError: 'Please select the invoice currency type',
    invoiceCountryTypeBlankError: 'Please select the country',
    invoiceDescTypeBlankError: 'Please enter the description',

    newTran: 'New Transaction',
    modifyCust: 'Modify Customer',
    manuallAddCust: 'Manually add Customer',
    selectCust: 'Select Customer',
    invoice: 'Invoice',
    invoiceUpload: 'Upload CSV',
    excelUpload: 'Upload Excel',

    profType: 'Type',
    invoiceCurrency: 'Currency',
    regiDate: 'Registration Date',
    invoiceRegiDate: 'Registration Date',
    invoiceDesc: 'Description',
    invoiceDesCountry: 'Destination Country',
    invoiceFractional: 'Fractional',
    invoiceSelectFractional: 'Select Fractional',
    invoiceDesProvince: 'Destination Province',

    profPerf: 'Professional Performance',
    profperfTitle1: 'Accounting Consultancy',
    profperfTitle2: 'Drafting Budget Assistants',
    profperfTitle3: 'Tax Consultancy',
    profperfTitle4: 'Company Consultancy for Mergers',
    profperfTitle5: 'Contractual Consultancy for mergers',
    value: 'Value',
    valueData1: 'Indeterminate',
    valueData2: 'Determinate',
    riskAsst: 'Risk Assessment',
    riskAsst1: 'Low',
    riskAsst2: 'Medium',
    riskAsst3: 'High',
    listedUserList: 'All Users List',
    NA: 'N/A',
    mainData: 'Main Data',
    fiscal: 'Fiscal code',
    vatNo: 'VAT Number',
    firstN: 'First Name',
    lastN: 'Last Name',
    commonFB: 'Common Foreign Birth',
    performAct: 'Performed Activity',
    businesN: 'Business Name',
    legalN: 'Legal Nature',
    businesS: 'Business Sector',
    muniFH: 'Municipality of foreign headquarters',
    DOB: 'Date of Birth',
    BS: 'Birth State',
    BP: 'Birth Province',
    AC: 'Ateco Code',
    ERD: 'End of Relationship Date',
    HS: 'Home state',
    Residncy: 'Residence',
    ResiAdd: 'Residence Address',
    HeadQAdd: 'Headquarters Address',
    domData: 'Domicile',
    domCountry: 'Country of Domicile',
    domProvince: 'Province of Domicile',
    domMFD: 'Municipality of Foreign Domicile',
    domZipCode: 'Domicile Zipcode',
    domHomeAdd: 'Home address',

    ReState: 'Residence State',
    CFR: 'Common Foreign Residence',
    Star: '*',
    PR: 'Postcode Residence',
    DER: 'Domicile equal to residence',

    //customer validation msg
    fiscalCodeBlankError: 'Please enter fiscal code',
    vatCodeBlankError: 'Please enter vat code',
    userDOBBlankError: 'Please enter the user date of birth',
    commonForeignBlankError: 'Please enter common foreign birth',
    birthCounteryBlankError: 'Please enter the user birth country',
    birthStateBlankError: 'Please enter the user state code',
    performedActivityBlankError: 'Please enter the performed activity',
    businessNameBlankError: 'Please enter business name',
    legalNatureBlankError: 'Please enter the legal nature',
    businessSectorBlankError: 'Please enter the business sector',
    atecoCodeBlankError: 'Please select the ateco code',
    MFHBlankError: 'Please enter the municipality of foreign headquarters',
    CFRBlankError: 'Please enter common foreign regidency',
    postCodeBlankError: 'Please enter user post code',
    numberOnlyError: 'Legal code accept only the number',

    //API messages:
    somethingWentWrong: 'Something went wrong, Please try again later',
    closeTicket: 'Close Ticket',
    reopenTicket: 'Reopen Ticket',
    verificationTypeFirst: 'Ordinary',
    verificationTypeSecond: 'Simplified',
    verificationTypeThird: 'Strengthened',

    //filter options
    all: 'All',
    compliance: 'Compliance',
    nonCompliance: 'Non Compliance',
    partialCompliance: 'Partially Compliance',
    open: 'Open',
    close: 'Closed',
    add: 'Add',
    createUserTickets: 'Create Ticket',

    //support type
    operationalQuery: ' Operational Related Query',
    contractQuery: ' Contract Related Query',
    transactionQuery: ' Transactional Related Query',
    notAble: 'Not available',
    customerFolderDetails: 'Customer Folder',

    //ticket validation
    ticketSubjectBlankError: 'Please enter ticket subject',
    ticketDetailsError: 'Ticket details must be combination of characters',
    ticketSubjectError: 'Ticket subject must be combination of characters',
    ticketTypeBlankError: 'Please enter ticket type',
    ticketDetailsBlankError: 'Please enter ticket details',
    supportTypeSelection: 'Choose the support type',
    dateIdentity: 'Please select the date identity',
    noData: 'No Data Available',
    noCust: 'No Customer Available',
    yearWise1: '2021',
    yearWise2: '2020',
    yearWise3: '2019',
    yearWise4: '2018',
    yearWise5: '2017',
    yearWise6: '2016',
    yearWise7: '2015',
    uploadedBy: 'Uploaded By',
    uploadedOn: 'Upload On',
    signatureType: 'Customer Signature',
    docType: 'Document Type',
    search: 'Search',
    nonCompl: 'Non Compliance',
    partialComp: 'Partially Compliance',

    //headingText
    typeofsubject: 'Type of subject',
    seriesofQuestion: 'Series Of Questions',
    madeBy: 'Made By',
    notes: 'Notes',
    reason: 'Reason',
    invoiceSelectReason: 'Selected Reason',
    prof: 'Professional',
    selectedProf: 'Selected Professional',
    uploadDoc: 'Upload document',
    custCounty: 'Customer country',
    custProvinces: 'customer Provinces',
    amountType: 'Amount type',
    amount: 'Amount',
    coin: 'Coin',
    paymentMethod: 'Payment Method',
    newPerfo: 'New Performance',
    tradeName: 'Trade name',
    attorney: 'Attorney',
    selectType: 'Select Type',
    uploadAnotherDoc: 'Upload another document',
    uploadChamberDoc: 'Upload Chamber of commerce document',
    selectFromExis: 'Select from existing',
    addNew: 'Add New',
    stateBirth: 'State of birth',
    mBirthabroad: 'Municipality of birth abroad',
    updateType: 'Update type',
    updateMan: 'Upload manually',
    resState: 'State of Residence',
    resCity: 'City of residence',
    pCodeRes: 'Postal code of residence',
    domResi: 'Domicile equal to residence',
    typeDoc: 'Type of document',
    headquarter: 'Headquarters',
    munHead: 'Municipality of Headquarter',
    address: 'Address',
    state: 'State',
    city: 'City',
    identityDoc: 'Identity Document',
    nominyData: 'Date of Nomination',
    identiData: 'Identification date',
    uploadChamberDoc: 'Upload Chamber of Commerce Document',
    provResi: 'Province of residence',
    selectPro: 'Select Province',
    effOwner: 'Effective owner',
    addSub: 'ADD SUBJECT',
    dataAcqu: 'Data acquired through',
    engageStartData: 'Engagement start date',
    endDateassign: 'End date of assignment',
  },
});

export default strings;
