/* eslint-disable no-undef */
export default WebService = {
  // BASE_URL: "https://demo-alavie.bestremoteteams.xyz/api/",
  // UNIQUE_ID_URL: "demo-alavie.bestremoteteams.xyz",
  BASE_URL: "https://alaviedev.alvinnova.com/api/", // New server
  UNIQUE_ID_URL: "alaviedev.alvinnova.com",
  // BASE_URL: 'https://api-alavie.project-demo-server.com/api/',
  PAGINATION_URL: "http://localhost/alavie-client-portal/public/api/",
  // BASE_URL: "http://clienta-alavie.project-demo-server.com/api/",
  CLIENTPORTAL: "client-portal",
  LOGIN: "login",
  FORGOT_PASSWORD: "forgot-password",
  USERPROFILE: "user-profile",
  UPDATEPROFILE: "update-profile",
  CHANGEPASSWORD: "change-password",
  VERIFY_OTP: "verify-login",
  LOGOUT: "logout",
  DASHBOARD: "dashboard-data",
  ALLNEWS: "all-news",
  CUSTOMERLIST: "customer-list",
  COUNTRYLIST: "country-list",
  STATELIST: "get-state-list",
  GETATECOLIST: "get-ateco-code",
  GETCUSTOMERDETAILS: "get-customer-details",
  UPDATECUSTOMERAPI: "update-customer",
  MANUALLYADDCUSTOMER: "manually-add-customer",
  TRANSACTIONDATA: "get-data-add-transaction",
  NEWTRANSACTION: "new-transaction",
  TICKETLIST: "tickets-list",
  RISKDATA: "get-risk-data",
  CREATENEWTICKET: "create-new-spport-ticket",
  CREATENEWCUSTOMER: "new-customer-create",
  GETRISKASSESMENT: "get-risk-assessment",
  GETNOTIFICATIONS: "user-notifications",
  CUSTOMERFOLDERLIST: "customer-folder-list",
  CUSTOMERFOLDEREXPAND: "customer-folder-expand",
  CLOSETICKET: "close-ticket",
  REOPENTICKET: "reopen-ticket",
  LEGALNATURE: "get-legal-nature",
  GETCUSTDETAILS: "customer-folder-details",
  MANDATORYDOCUPLOAD: "mandatory-doc-upload",
  OTHERDOCUPLOAD: "other-doc-upload",
  ADDTICKETCOMMENT: "add-ticket-comment",
  GETICKETCOMMENT: "get-ticket-comments",
  GETCUSTOMERQUESTIONLIST: "get-customer-questions-list",
  GETCHATLIST: "chat-users",
  SENDMESSAGE: "chat-send-message",
  LOADPREVIOUSMESSAGE: "chat-load-previous-conversation",
  GETCHATCOUNTLIST: "chat-message-count",
  GETTRANSACTIONVALUE: "get-value-transaction",
};
